package fch

var skillNames = map[int32]string{
	0:   "None",
	1:   "Swords",
	2:   "Knives",
	3:   "Clubs",
	4:   "Polearms",
	5:   "Spears",
	6:   "Blocking",
	7:   "Axes",
	8:   "Bows",
	9:   "ElementalMagic",
	10:  "BloodMagic",
	11:  "Unarmed",
	12:  "Pickaxes",
	13:  "WoodCutting",
	14:  "Crossbows",
	100: "Jump",
	101: "Sneak",
	102: "Run",
	103: "Swim",
	104: "Fishing",
	105: "Cooking",
	106: "Farming",
	107: "Crafting",
	108: "Dodge",
	110: "Ride",
	999: "All",
}

var playerStatNames = []string{
	"Deaths",
	"CraftsOrUpgrades",
	"Builds",
	"Jumps",
	"Cheats",
	"EnemyHits",
	"EnemyKills",
	"EnemyKillsLastHits",
	"PlayerHits",
	"PlayerKills",
	"HitsTakenEnemies",
	"HitsTakenPlayers",
	"ItemsPickedUp",
	"Crafts",
	"Upgrades",
	"PortalsUsed",
	"DistanceTraveled",
	"DistanceWalk",
	"DistanceRun",
	"DistanceSail",
	"DistanceAir",
	"TimeInBase",
	"TimeOutOfBase",
	"Sleep",
	"ItemStandUses",
	"ArmorStandUses",
	"WorldLoads",
	"TreeChops",
	"Tree",
	"TreeTier0",
	"TreeTier1",
	"TreeTier2",
	"TreeTier3",
	"TreeTier4",
	"TreeTier5",
	"LogChops",
	"Logs",
	"MineHits",
	"Mines",
	"MineTier0",
	"MineTier1",
	"MineTier2",
	"MineTier3",
	"MineTier4",
	"MineTier5",
	"RavenHits",
	"RavenTalk",
	"RavenAppear",
	"CreatureTamed",
	"FoodEaten",
	"SkeletonSummons",
	"ArrowsShot",
	"TombstonesOpenedOwn",
	"TombstonesOpenedOther",
	"TombstonesFit",
	"DeathByUndefined",
	"DeathByEnemyHit",
	"DeathByPlayerHit",
	"DeathByFall",
	"DeathByDrowning",
	"DeathByBurning",
	"DeathByFreezing",
	"DeathByPoisoned",
	"DeathBySmoke",
	"DeathByWater",
	"DeathByEdgeOfWorld",
	"DeathByImpact",
	"DeathByCart",
	"DeathByTree",
	"DeathBySelf",
	"DeathByStructural",
	"DeathByTurret",
	"DeathByBoat",
	"DeathByStalagtite",
	"DoorsOpened",
	"DoorsClosed",
	"BeesHarvested",
	"SapHarvested",
	"TurretAmmoAdded",
	"TurretTrophySet",
	"TrapArmed",
	"TrapTriggered",
	"PlaceStacks",
	"PortalDungeonIn",
	"PortalDungeonOut",
	"BossKills",
	"BossLastHits",
	"SetGuardianPower",
	"SetPowerEikthyr",
	"SetPowerElder",
	"SetPowerBonemass",
	"SetPowerModer",
	"SetPowerYagluth",
	"SetPowerQueen",
	"SetPowerAshlands",
	"SetPowerDeepNorth",
	"UseGuardianPower",
	"UsePowerEikthyr",
	"UsePowerElder",
	"UsePowerBonemass",
	"UsePowerModer",
	"UsePowerYagluth",
	"UsePowerQueen",
	"UsePowerAshlands",
	"UsePowerDeepNorth",
}
